from flask import Flask, request, jsonify
from flask_cors import CORS
import os
import requests
import html

app = Flask(__name__)
CORS(app)

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_GROUP_ID = os.getenv(
    "TELEGRAM_GROUP_ID",
    "-1003968349221"
)


@app.route("/")
def home():
    return jsonify({
        "status": "ok",
        "service": "KEYRADDIIN EXAM CENTER",
        "message": "Backend server is running."
    })


@app.route("/api/health")
def health():
    return jsonify({
        "status": "ok",
        "service": "KEYRADDIIN EXAM CENTER",
        "telegram_configured": bool(
            TELEGRAM_BOT_TOKEN
        ),
        "telegram_group": TELEGRAM_GROUP_ID
    })


@app.route("/api/send-result", methods=["POST"])
def send_result():

    if not TELEGRAM_BOT_TOKEN:
        return jsonify({
            "success": False,
            "message": "Telegram bot token is not configured."
        }), 500

    data = request.get_json(silent=True)

    if not data:
        return jsonify({
            "success": False,
            "message": "No result data received."
        }), 400

    required_fields = [
        "studentName",
        "grade",
        "examCode",
        "score",
        "total",
        "percentage",
        "correct",
        "wrong",
        "timeUsed",
        "status"
    ]

    missing_fields = [
        field
        for field in required_fields
        if field not in data
    ]

    if missing_fields:
        return jsonify({
            "success": False,
            "message": "Missing required fields.",
            "missing": missing_fields
        }), 400

    student_name = str(
        data.get("studentName", "")
    ).strip()

    grade = str(
        data.get("grade", "")
    ).strip()

    exam_code = str(
        data.get("examCode", "")
    ).strip()

    exam_title = str(
        data.get("examTitle", "")
    ).strip()

    subject = str(
        data.get("subject", "")
    ).strip()

    unit = str(
        data.get("unit", "")
    ).strip()

    score = data.get("score", 0)
    total = data.get("total", 0)
    percentage = data.get("percentage", 0)
    correct = data.get("correct", 0)
    wrong = data.get("wrong", 0)

    time_used = str(
        data.get("timeUsed", "00:00")
    ).strip()

    status = str(
        data.get("status", "")
    ).strip().upper()

    pass_mark = data.get("passMark", 50)

    if not student_name:
        return jsonify({
            "success": False,
            "message": "Student name is required."
        }), 400

    if not grade:
        return jsonify({
            "success": False,
            "message": "Grade is required."
        }), 400

    if not exam_code:
        return jsonify({
            "success": False,
            "message": "Exam code is required."
        }), 400

    student_name = html.escape(student_name)
    grade = html.escape(grade)
    exam_code = html.escape(exam_code)
    exam_title = html.escape(exam_title)
    subject = html.escape(subject)
    unit = html.escape(unit)
    time_used = html.escape(time_used)
    status = html.escape(status)

    status_icon = (
        "✅"
        if status == "PASSED"
        else "❌"
    )

    message = f"""
<b>🎓 KEYRADDIIN EXAM CENTER</b>

<b>📋 EXAMINATION RESULT</b>

👤 <b>Student:</b> {student_name}
🎓 <b>Grade:</b> {grade}

📚 <b>Subject:</b> {subject or "—"}
📖 <b>Unit:</b> {unit or "—"}

📝 <b>Exam:</b> {exam_title or "—"}

🔑 <b>Exam Code:</b>
<code>{exam_code}</code>

━━━━━━━━━━━━━━━━━━

🏆 <b>Score:</b> {score} / {total}
📈 <b>Percentage:</b> {percentage}%

✅ <b>Correct:</b> {correct}
❌ <b>Wrong:</b> {wrong}

⏱ <b>Time Used:</b> {time_used}

🎯 <b>Pass Mark:</b> {pass_mark}%

━━━━━━━━━━━━━━━━━━

{status_icon} <b>Status: {status}</b>

━━━━━━━━━━━━━━━━━━

🤖 <i>Automatically generated by
KEYRADDIIN EXAM CENTER</i>
""".strip()

    telegram_url = (
        "https://api.telegram.org/bot"
        f"{TELEGRAM_BOT_TOKEN}/sendMessage"
    )

    telegram_params = {
        "chat_id": TELEGRAM_GROUP_ID,
        "text": message,
        "parse_mode": "HTML"
    }

    try:

        response = requests.get(
            telegram_url,
            params=telegram_params,
            timeout=15
        )

        try:
            telegram_data = response.json()

        except ValueError:

            print(
                "Telegram returned invalid JSON:",
                response.status_code,
                response.text
            )

            return jsonify({
                "success": False,
                "message": "Invalid response from Telegram."
            }), 502

        if not response.ok:

            print(
                "Telegram API error:",
                response.status_code,
                response.text
            )

            return jsonify({
                "success": False,
                "message": "Telegram API request failed.",
                "telegram_error": telegram_data
            }), 502

        if not telegram_data.get("ok"):

            print(
                "Telegram rejected message:",
                telegram_data
            )

            return jsonify({
                "success": False,
                "message": "Telegram rejected the message.",
                "telegram_error": telegram_data
            }), 502

        telegram_message_id = (
            telegram_data
            .get("result", {})
            .get("message_id")
        )

        print(
            "Telegram result sent successfully:",
            telegram_message_id
        )

        return jsonify({
            "success": True,
            "message":
                "Result sent successfully to Telegram.",
            "telegram_message_id":
                telegram_message_id
        }), 200

    except requests.RequestException as error:

        print(
            "Telegram connection error:",
            error
        )

        return jsonify({
            "success": False,
            "message":
                "Could not connect to Telegram."
        }), 502


@app.errorhandler(404)
def not_found(error):

    return jsonify({
        "success": False,
        "message": "API endpoint not found."
    }), 404


@app.errorhandler(500)
def internal_error(error):

    return jsonify({
        "success": False,
        "message": "Internal server error."
    }), 500


if __name__ == "__main__":

    port = int(
        os.getenv(
            "PORT",
            "5000"
        )
    )

    app.run(
        host="0.0.0.0",
        port=port,
        debug=False
    )
